[tool.ruff]
target-version = "py313"
line-length = 100
extend-exclude = [
  "alembic/",          # migrations; often noisy for linters
  "node_modules/",     # just in case
  ".venv/",
]

[tool.ruff.lint]
select = ["E", "F"]
ignore = []
